services:
  sift-toolbox:
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Updated to the correct Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    
  # Development service (optional)
  sift-toolbox-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    profiles:
      - dev

  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: sift
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg/local-data:/data
      - ./data/pg/pgdata:/var/lib/postgresql/data
