services:
  sift-toolbox:
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Updated to the correct Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    
  # Development service (optional)
  sift-toolbox-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    profiles:
      - dev

  postgres_db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sift_backend/db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    restart: unless-stopped

volumes:
  pg_data:
